[package]
name = "sync-server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
futures-util = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
tokio-tungstenite = "0.23.1"
url = "2.5.2"
warp = "0.3.7"
